export const PUSH_MODAL_WINDOW = 'PUSH_MODAL_WINDOW';
export const INSERT_MODAL_WINDOW = 'INSERT_MODAL_WINDOW';
export const POP_MODAL_WINDOW = 'POP_MODAL_WINDOW';
export const SHIFT_MODAL_WINDOW = 'SHIFT_MODAL_WINDOW';
export const CLEAR_MODAL_WINDOWS = 'CLEAR_MODAL_WINDOWS';
